name: Generate Profile Contribution Images

on:
  schedule: # 06:00 CST == 11:00 UTC
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  generate-images:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Generate Profile Contribution Images
        uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name jpfulton
          git config user.email jpatrick.fulton@gmail.com
          git add -A .
          git commit -m "generated"
          git push